services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=blog_nico
      - MYSQL_USER=root
      - MYSQL_PASSWORD=nicolas
      - MYSQL_ROOT_PASSWORD=nicolas
